### ISSUE TITLE
Refactoring and testing

### ISSUE THREAD

**Issue by saurabh-ku** [kenrick95/c4#10]
Hey,

I am new to TypeScript and open source and I found your game to be an amazing repository to learn and practice TypeScript by refactoring and writing tests for your code. 

I would like to contribute a little to the repo on a daily basis and would love it if you could review my code daily and suggest changes.

**Comment by kenrick95** [comment]
Sure, you can list down first what are the changes you want to make. I'd suggest to not make it so ambitious to completely refactor the whole project, but with one small step at a time. Perhaps, integrating a test runner and writing a test to the util.ts file could be a start? Thanks!

**Comment by kenrick95** [comment]
Closing, due to inactivity
