### ISSUE TITLE
Remove ES2015 Promise from browser requirement at Readme

### ISSUE THREAD

**Issue by kenrick95** [kenrick95/c4#11]
At README.md, ["Browser compatibility" section](https://github.com/kenrick95/c4#browser-compatibility), it still mentions 

> Require browser that supports ES2015's Promise.

This line at [README.md](https://github.com/kenrick95/c4/blob/master/README.md) should be removed because I have already included a Promise polyfill in https://github.com/kenrick95/c4/blob/master/src/app.ts#L1

**Comment by f1xer** [comment]
Hi! I'm happy to try and fix this for you if that's ok?
