### ISSUE TITLE
Playing online against another human.

### ISSUE THREAD

**Issue by Mengel38** [kenrick95/c4#13]
It would be nice if one could play against another human over the network / Internet or however they have access to the server running the game. If you plan for something like this on your own, I encourage you to implement this.
If you do not plan this on your own yet, I am willing to make this my own task and submit a PR when I am ready.
Please let me know what you think about it. :)

**Comment by kenrick95** [comment]
Hi @Mengel38 , thanks for your suggestion. That's definitely in my wish list! But unfortunately I'm not able to work in this at the moment. Feel free to fork this project out (and send a PR, maybe)? Thanks!

**Comment by Mengel38** [comment]
Hi @kenrick95, I will do so. Thank you for your quick response and your approval.

**Comment by kenrick95** [comment]
Hi @Mengel38, do you have any plan to share regarding this? Thanks

**Comment by Mengel38** [comment]
Hello @kenrick95 ,
sorry for not working on this yet.
I considered quite a few approaches for the challenge on how to make remote machines connect to each other.

1) Use WebRTC.

After the initialization of the connection, you have a peer-to-peer connection between two browsers.
Advantages:
+Direct connection
+Most of the time, there is no load a server needs to handle.
+Transfer of binary data possible.
Disadvantages:
-This technology is quite new, so possibly unstable and not good in regard of browser-compatibilty.
-Because we are online, we would require a server which negotiates the connection details between two clients.
-EVERY data transfer is encrypted. This might be additional load client-side wise which might not be worth it.

2) Use XMLHttpRequests (additional web requests).

When the "game" (the website and the script files) are successfully loaded in the browser, additional HTTP requests will follow for everything else.
Advantages:
+HTTP traffic can go through almost all firewalls.
+If you are running a web server anyways, depending on the technology you use for this, offering the online mode after implementation is not a big feat.
Disadvantages:
-Headers. You cannot avoid to transfer them every time.
-Both sides are required to poll independently the server to find out if the other side is still connected, made a move, etc.

3) Use WebSockets (continous data transfer).

Another connection to a special server can occur after the game being fully loaded.
WebSockets are, somewhat special. They are no true sockets, but they allow for asynchronous data flow between servers and clients / web browsers. 
Advantages:
+Event-based handling of data is possible.
Disadvantages:
-Web servers do not really support this protocol, but you can use them as reverse-proxies.
-Also, WebSockets are not too old yet.
-The need to ALWAYS need a new server.

I would definitely prefer option 2) for this small game. 1) and 3) might be way too complex for this. And I think we cannot avoid adding any complexity at all with online modes, as the web application is just client-only now.
I plan to either use Node.js, Java or PHP (most likely Node.js) to implement the required server.

I will start when I am at full strength.

**Comment by Mengel38** [comment]
Hi @kenrick95.

I am sorry I am keeping you waiting here alot. I think I do not have too good news in regard of this issue:

* Both given my lack of competence with especially TypeScript and my queue in regard of a project very important to me, I think I might not be able to actually implement what I thought of. This is rather embarrassing to admit publicly, but I think the only right thing I can do now is to let you know of this.

* I should have checked the pre-requirements more carefully before basically jumping into this.

I am sorry for wasting your time here.

**Comment by kenrick95** [comment]
Hi, it's ok, no worries! 😁
