### ISSUE TITLE
Maybe is it a bug

### ISSUE THREAD

**Issue by growvv** [kenrick95/c4#19]
When player 1 puts a chess in the middle column, and then it is always placed on the top of player 2, it is always a draw. I don't know if this is a bug
![](https://cdn.jsdelivr.net/gh/growvv/image-bed/images/20200728095406.png)

**Comment by kenrick95** [comment]
Somehow this issue slipped me, but I do not think it's a bug. The "AI" is not perfect and could behaves differently from what is expected from a human
