### ISSUE TITLE
Stupid turn

### ISSUE THREAD

**Issue by code-hunger** [kenrick95/c4#3]
Not sure if it counts as a bug, but I find it too obvious.
Just placed that red on the 6th column and the game put a blue on the first. Or was it by design?
![screenshot](http://s15.postimg.org/9xp7c9g63/connect_4.png)
Log, if can help: http://pastebin.com/AAAjUXEw

**Comment by kenrick95** [comment]
Certainly a bug, but this makes the game winnable for the human player. :stuck_out_tongue_closed_eyes: 

Maybe I'll look into it one day. Thanks for reporting.
